spring:
  application:
    name: smwu-itple

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maeumgil?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: spring
    password: Spring1234!

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        oauth2: DEBUG

kakaopay :
  secretKey : "DEV1E4CA68D7F1F8B36B8EEC8ADFEC88FDD4A324"
  cid : "TC0ONETIME"