spring:
  application:
    name: smwu-itple

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-15-164-102-9.ap-northeast-2.compute.amazonaws.com:3306/maeumgil?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: spring
    password: Spring1234!

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000  # 5분
      max-lifetime: 1800000  # 30분
      keepalive-time: 300000  # 5분마다 연결 유지


  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
  port: 8081

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: maeumgil
    stack:
      auto: false

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        oauth2: DEBUG

kakaopay :
  secretKey : "DEV1E4CA68D7F1F8B36B8EEC8ADFEC88FDD4A324"
  cid : "TC0ONETIME"